### ISSUE TITLE
Time Zone Setting

### ISSUE THREAD

**Issue by zmbc** [Eupeodes/gh#11]
First of all, thanks for the website, I use it every day.

The only problem I have is that the calendar seems to be wrong, which I think is a time zone issue. I'm in the PST time zone and it's the morning of February 9th as I write this, but the 10th is selectable (and displays nothing, of course). I can't repro it right now, but sometimes the next day is selected by default (maybe when the default time zone is advanced beyond the Dow opening time?).

**Comment by Eupeodes** [comment]
Making the next data available is because of the eastern hashes which are one day ahead of the western. So in Europe the hash for the 10th is already available. I see three possible solutions here:
1. Just leave it
2. Add some notice that in west of 30 degrees west a day less is available
3. Make the last day available or unavailable depending on whether the map center is to the east or to the west of 30 degrees west

Regarding the setting the wrong date by default, that is caused by taking the date of the server by default, I have to rewrite that to taking the date of the user if no date is given trough an url parameter. Thanks for reporting, this is a bug I would have a hard time detecting since the server is in the same timezone as I am.

**Comment by zmbc** [comment]
Thanks for the quick response and fix! I wasn't aware of the "east of 30" exception.

As far as the three solutions: In my mind, days should only be clickable if there is data for them, so 3 seems the best.

**Comment by Eupeodes** [comment]
I've reconsidered this and I came to the conclusion that option 3 will cause new problems with the global hash. The global hash uses the dow from the day before, just like with the 30W rule. The dow can fall west of the 30 degrees west line. If I would implement option 3 that would mean that the dow would not be visible until after midnight. I will work on a solution more like 2, but have to see in what form I will implement this.

**Comment by zmbc** [comment]
Very interesting. I didn't know much about the globalhash--I always thought it was a crazy challenge to reach a random spot on the globe in less than 24 hours. Now that I find out it's nearly 48 hours, it seems like a piece of cake. :stuck_out_tongue:

Actually, now that I know this, everything makes a lot more sense. The next day is clickable because there **is** data for it, just for the global hash. With that in mind, I agree a notice is the best thing to do. 

Also--have you considered having some type of "beginner's guide" content on the website? I'm kind of amazed that I didn't know about the 30W or globalhash rules. In addition/as part of the notice, it might be nice to explain the very basics and some of the quirks of how the geohash is calculated (leaving out all the technical details).

**Comment by Eupeodes** [comment]
I have considered the 'beginners guide', decided not to have that because that is information that is on the wiki, I did add a link to the wiki in the help function.

I am also working on the notification about the 30W rule, hope to finish that within a few days

**Comment by Eupeodes** [comment]
Thanks to this issue I found another bug around 180 degrees, fixed that as well when implementing the notice.
